### ISSUE TITLE
Record video for Milestone 1 in Spanish

### ISSUE THREAD

**Issue by garcia-alejandro** [hashed-io/hashed-marketplaces-ui#18]
# Introduction
- [x] Record Introduction
* A brief introduction to Milestone 1, reminding what was described on the Grant
* [Diagrams](https://app.diagrams.net/?state=%7B%22ids%22:%5B%221v5aZaSNxySvfwBYJzFbrhfYYxtiMacKt%22%5D,%22action%22:%22open%22,%22userId%22:%22111156622522483905804%22,%22resourceKeys%22:%7B%7D%7D)
# Repos
- [x] Record Important Repos 
* [Market UI](https://github.com/Afloat-Inc/marketplaces-ui)
* [Pallets](https://github.com/Afloat-Inc/pallets)
* [Private Client](https://github.com/Afloat-Inc/private-client-api)
* [Private server](https://github.com/Afloat-Inc/private-server)
# Set profile
- [x] Set Profile part 1
  *  Demo page to ensure the private data
- [x] Set Profile part 2
  * Create Marketplace
  * Apply for marketplace (Apply Form)
  * Show custodian input
- [x] Set Profile part 3
-  Show Custody Page
# KYC Admin
- [x] Record KYC admin section
* Shows the Administrator panel
* Approve an user
* Reject an user
- [x] Deliverable Video

**Comment by garcia-alejandro** [comment]
# Introduction Video
* [Introduction Spanish](https://drive.google.com/file/d/1FQEUVg3Jlz5HyuC7qT0nvY0-164tBFsI/view?usp=sharing)

**Comment by garcia-alejandro** [comment]
# Repos
* [Important Repos Spanish](https://drive.google.com/file/d/17JyOHVlMOHj4Pyy-o0Sz6rqUo4XqIFjT/view?usp=sharing)

**Comment by garcia-alejandro** [comment]
# Set Profile
Part 1. Private service
[Private Service](https://drive.google.com/file/d/1Vb2Xd2R2PnKDzDHKyXBhj05OCJ9lN4hc/view?usp=sharing)
Part 2. Apply Form
[Apply Form](https://drive.google.com/file/d/1T8x2gBuMo48iqT-0ye6p1PQnKhzXoTRN/view?usp=sharing)
Part 3. Custodian
[Custodian] (https://drive.google.com/file/d/12agpm-Aa2ICuxl50cn2dsm3aUbW8lNDk/view?usp=sharing)

**Comment by garcia-alejandro** [comment]
# KYC Admin
[Panel] (https://drive.google.com/file/d/1H8tJWjAeb7jAxg6TD2uqeLQFHRb_GiXy/view?usp=sharing)

**Comment by garcia-alejandro** [comment]
# Video 
[Youtube](https://www.youtube.com/watch?v=oOlda7FZa_M)
